### PR TITLE
feat: Login logic, order api

### PR DESCRIPTION
**Pull request by KhoaAnhDoNguyen**

### CODE REVIEW

**Review by namdnhn — APPROVED** [review]

**Review by letanhoaUIT — APPROVED** [review]

**Comment by KhoaAnhDoNguyen** [comment]
Ready

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Conflic rồi em

**Comment by KhoaAnhDoNguyen** [comment]
Ready

**Review by namdnhn — APPROVED** [review]

**Comment by KhoaAnhDoNguyen** [comment]
Ready

**Review by ghost — APPROVED** [review]

**Pull request merged**
