### PR TITLE
Fix/update cart

### PR DESCRIPTION
**Pull request by letanhoaUIT**
update increase|decrease|remove for cart

### CODE REVIEW

**Review by KhoaAnhDoNguyen — APPROVED** [review]

**Comment by letanhoaUIT** [comment]
ready

**Comment by namdnhn** [comment]
2 commit

**Comment by letanhoaUIT** [comment]
> 2 commit

fix rồi nha :>

**Review by namdnhn — APPROVED** [review]

**Comment by letanhoaUIT** [comment]
ready

**Review by ghost — APPROVED** [review]

**Pull request merged**
